"""ST-12 — End-to-end integration tests for the complete analytics pipeline.

Tests the full pipeline for each of the three reference datasets:
    datasets/titanic_like.csv  → classification
    datasets/house_prices.csv  → regression
    datasets/customers.csv     → clustering (no supervised target)

Pipeline stages verified:
    Ingestion → Preprocessing → Profiling → EDA → Visualization
    → Machine Learning → GenAI (mocked) → NL Query → Reporting

Design constraints
------------------
* No real watsonx.ai API calls are made — the client is always mocked.
* random_state=42 is used everywhere for reproducibility.
* Tests do not modify any existing test or source file.
"""

from __future__ import annotations

import tempfile
from pathlib import Path
from typing import Any
from unittest.mock import MagicMock, patch

import pandas as pd
import plotly.graph_objects as go
import pytest

# ---------------------------------------------------------------------------
# Dataset paths
# ---------------------------------------------------------------------------

_DATASETS_DIR = Path(__file__).parent.parent / "datasets"
_TITANIC = _DATASETS_DIR / "titanic_like.csv"
_HOUSE = _DATASETS_DIR / "house_prices.csv"
_CUSTOMERS = _DATASETS_DIR / "customers.csv"


def _skip_if_missing(path: Path) -> None:
    if not path.exists():
        pytest.skip(f"Reference dataset '{path.name}' not found.")


# ---------------------------------------------------------------------------
# Shared mock watsonx client fixture
# ---------------------------------------------------------------------------


@pytest.fixture()
def mock_watsonx_client() -> MagicMock:
    """A WatsonxClient mock that returns a canned string instead of calling the API."""
    client = MagicMock()
    client.is_configured = True
    client.generate.return_value = "Mock AI insight generated by watsonx."
    return client


# ===========================================================================
# 1. INGESTION
# ===========================================================================


class TestIngestionAllDatasets:
    """Verify that every reference dataset loads into a valid DataFrame."""

    def _loader(self):
        from src.ingestion.data_loader import DataLoader
        return DataLoader()

    def test_titanic_loads(self):
        _skip_if_missing(_TITANIC)
        df = self._loader().load(_TITANIC)
        assert isinstance(df, pd.DataFrame)
        assert not df.empty
        assert len(df.columns) > 0

    def test_titanic_has_expected_columns(self):
        _skip_if_missing(_TITANIC)
        df = self._loader().load(_TITANIC)
        # After normalisation, column names are lowercase
        assert "survived" in df.columns
        assert "pclass" in df.columns

    def test_house_prices_loads(self):
        _skip_if_missing(_HOUSE)
        df = self._loader().load(_HOUSE)
        assert isinstance(df, pd.DataFrame)
        assert not df.empty

    def test_house_prices_has_expected_columns(self):
        _skip_if_missing(_HOUSE)
        df = self._loader().load(_HOUSE)
        assert "saleprice" in df.columns

    def test_customers_loads(self):
        _skip_if_missing(_CUSTOMERS)
        df = self._loader().load(_CUSTOMERS)
        assert isinstance(df, pd.DataFrame)
        assert not df.empty

    def test_customers_has_expected_columns(self):
        _skip_if_missing(_CUSTOMERS)
        df = self._loader().load(_CUSTOMERS)
        # Column name will be normalised from "Annual Income (k$)"
        cols_lower = [c.lower() for c in df.columns]
        assert any("annual" in c or "income" in c for c in cols_lower)

    def test_all_three_datasets_non_empty(self):
        loader = self._loader()
        for path in [_TITANIC, _HOUSE, _CUSTOMERS]:
            _skip_if_missing(path)
            df = loader.load(path)
            assert len(df) > 0, f"{path.name} produced empty DataFrame"
            assert len(df.columns) > 0, f"{path.name} has no columns"


# ===========================================================================
# 2. PREPROCESSING
# ===========================================================================


class TestPreprocessingAllDatasets:
    """Verify preprocessing produces valid output for each reference dataset."""

    def _load(self, path: Path) -> pd.DataFrame:
        from src.ingestion.data_loader import DataLoader
        return DataLoader().load(path)

    def test_titanic_preprocessing_valid_output(self):
        _skip_if_missing(_TITANIC)
        from src.preprocessing.preprocessor import run_preprocessing
        df = self._load(_TITANIC)
        result_df, summary = run_preprocessing(df)
        assert isinstance(result_df, pd.DataFrame)
        assert not result_df.empty
        assert isinstance(summary, dict)
        assert "steps" in summary
        assert "final_shape" in summary

    def test_titanic_preprocessing_no_missing_values(self):
        _skip_if_missing(_TITANIC)
        from src.preprocessing.preprocessor import run_preprocessing
        df = self._load(_TITANIC)
        result_df, _ = run_preprocessing(df, missing_strategy="mean")
        # After imputation all numeric columns should have no nulls
        numeric_cols = result_df.select_dtypes(include="number").columns
        assert result_df[numeric_cols].isnull().sum().sum() == 0

    def test_house_prices_preprocessing_valid_output(self):
        _skip_if_missing(_HOUSE)
        from src.preprocessing.preprocessor import run_preprocessing
        df = self._load(_HOUSE)
        result_df, summary = run_preprocessing(df)
        assert isinstance(result_df, pd.DataFrame)
        assert not result_df.empty
        assert len(summary["steps"]) > 0

    def test_customers_preprocessing_valid_output(self):
        _skip_if_missing(_CUSTOMERS)
        from src.preprocessing.preprocessor import run_preprocessing
        df = self._load(_CUSTOMERS)
        result_df, summary = run_preprocessing(df)
        assert isinstance(result_df, pd.DataFrame)
        assert not result_df.empty

    def test_preprocessing_shape_preserved(self):
        """Row count must not increase; columns may grow (OHE/datetime features)."""
        _skip_if_missing(_TITANIC)
        from src.preprocessing.preprocessor import run_preprocessing
        df = self._load(_TITANIC)
        result_df, _ = run_preprocessing(df)
        # Rows may decrease (duplicate removal) but never increase
        assert len(result_df) <= len(df)

    def test_preprocessing_summary_records_each_step(self):
        _skip_if_missing(_HOUSE)
        from src.preprocessing.preprocessor import run_preprocessing
        df = self._load(_HOUSE)
        _, summary = run_preprocessing(df)
        for step in summary["steps"]:
            assert step in summary, f"Step '{step}' key missing from summary"


# ===========================================================================
# 3. PROFILING
# ===========================================================================


class TestProfilingAllDatasets:
    """Verify profiling produces a valid ProfileReport for each dataset."""

    def _load(self, path: Path) -> pd.DataFrame:
        from src.ingestion.data_loader import DataLoader
        return DataLoader().load(path)

    def _assert_valid_report(self, report: dict) -> None:
        required_keys = [
            "shape", "memory_usage_bytes", "dtypes", "null_counts",
            "null_percentages", "cardinality", "numeric_stats",
            "categorical_stats", "correlation",
        ]
        for key in required_keys:
            assert key in report, f"ProfileReport missing key '{key}'"
        assert report["shape"]["rows"] > 0
        assert report["shape"]["columns"] > 0

    def test_titanic_profile_valid(self):
        _skip_if_missing(_TITANIC)
        from src.profiling.data_profiler import profile_dataframe
        df = self._load(_TITANIC)
        report = profile_dataframe(df)
        self._assert_valid_report(report)

    def test_house_prices_profile_valid(self):
        _skip_if_missing(_HOUSE)
        from src.profiling.data_profiler import profile_dataframe
        df = self._load(_HOUSE)
        report = profile_dataframe(df)
        self._assert_valid_report(report)

    def test_customers_profile_valid(self):
        _skip_if_missing(_CUSTOMERS)
        from src.profiling.data_profiler import profile_dataframe
        df = self._load(_CUSTOMERS)
        report = profile_dataframe(df)
        self._assert_valid_report(report)

    def test_profile_numeric_stats_have_expected_fields(self):
        _skip_if_missing(_TITANIC)
        from src.profiling.data_profiler import profile_dataframe
        df = self._load(_TITANIC)
        report = profile_dataframe(df)
        for col, stats in report["numeric_stats"].items():
            for field in ("count", "mean", "median", "std", "min", "max"):
                assert field in stats, f"Numeric stats for '{col}' missing '{field}'"

    def test_profile_correlation_has_pearson_spearman(self):
        _skip_if_missing(_HOUSE)
        from src.profiling.data_profiler import profile_dataframe
        df = self._load(_HOUSE)
        report = profile_dataframe(df)
        assert "pearson" in report["correlation"]
        assert "spearman" in report["correlation"]

    def test_profile_report_json_serialisable(self):
        """All values in the ProfileReport must be JSON-serialisable primitives."""
        import json
        _skip_if_missing(_CUSTOMERS)
        from src.profiling.data_profiler import profile_dataframe
        df = self._load(_CUSTOMERS)
        report = profile_dataframe(df)
        # This must not raise
        json.dumps(report)


# ===========================================================================
# 4. EDA
# ===========================================================================


class TestEDAAllDatasets:
    """Verify EDA produces valid results for each reference dataset."""

    def _load(self, path: Path) -> pd.DataFrame:
        from src.ingestion.data_loader import DataLoader
        return DataLoader().load(path)

    def test_titanic_eda_valid(self):
        _skip_if_missing(_TITANIC)
        from src.eda.eda_engine import run_eda
        df = self._load(_TITANIC)
        result = run_eda(df, target_column="survived", task_type="classification")
        assert isinstance(result, dict)
        assert "univariate" in result
        assert "bivariate" in result
        assert "groupby" in result
        assert "target_analysis" in result

    def test_house_prices_eda_valid(self):
        _skip_if_missing(_HOUSE)
        from src.eda.eda_engine import run_eda
        df = self._load(_HOUSE)
        result = run_eda(df, target_column="saleprice", task_type="regression")
        assert isinstance(result, dict)
        assert "univariate" in result
        assert "target_analysis" in result

    def test_customers_eda_valid(self):
        _skip_if_missing(_CUSTOMERS)
        from src.eda.eda_engine import run_eda
        df = self._load(_CUSTOMERS)
        result = run_eda(df)
        assert isinstance(result, dict)
        assert "univariate" in result
        assert "bivariate" in result

    def test_eda_univariate_contains_numeric_and_categorical(self):
        _skip_if_missing(_TITANIC)
        from src.eda.eda_engine import run_eda
        df = self._load(_TITANIC)
        result = run_eda(df)
        assert "numeric" in result["univariate"]
        assert "categorical" in result["univariate"]
        assert len(result["univariate"]["numeric"]) > 0

    def test_eda_bivariate_has_correlation(self):
        _skip_if_missing(_HOUSE)
        from src.eda.eda_engine import run_eda
        df = self._load(_HOUSE)
        result = run_eda(df)
        corr = result["bivariate"]["correlation"]
        assert "pearson" in corr
        assert len(corr["pearson"]) > 0

    def test_eda_classification_target_analysis_has_class_distribution(self):
        _skip_if_missing(_TITANIC)
        from src.eda.eda_engine import run_eda
        df = self._load(_TITANIC)
        result = run_eda(df, target_column="survived", task_type="classification")
        ta = result["target_analysis"]
        assert "class_distribution" in ta
        assert ta["n_classes"] >= 2

    def test_eda_regression_target_analysis_has_distribution(self):
        _skip_if_missing(_HOUSE)
        from src.eda.eda_engine import run_eda
        df = self._load(_HOUSE)
        result = run_eda(df, target_column="saleprice", task_type="regression")
        ta = result["target_analysis"]
        assert "distribution" in ta
        assert ta["distribution"]["count"] > 0


# ===========================================================================
# 5. VISUALIZATION
# ===========================================================================


class TestVisualizationAllDatasets:
    """Verify chart builder functions return valid Plotly Figure objects."""

    def _load(self, path: Path) -> pd.DataFrame:
        from src.ingestion.data_loader import DataLoader
        return DataLoader().load(path)

    def _assert_plotly_figure(self, fig: Any) -> None:
        assert isinstance(fig, go.Figure), f"Expected go.Figure, got {type(fig)}"

    def test_titanic_histogram(self):
        _skip_if_missing(_TITANIC)
        from src.visualization.chart_builder import histogram
        df = self._load(_TITANIC)
        fig = histogram(df, "age")
        self._assert_plotly_figure(fig)

    def test_titanic_bar_chart(self):
        _skip_if_missing(_TITANIC)
        from src.visualization.chart_builder import bar_chart
        df = self._load(_TITANIC)
        fig = bar_chart(df, "sex")
        self._assert_plotly_figure(fig)

    def test_titanic_pie_chart(self):
        _skip_if_missing(_TITANIC)
        from src.visualization.chart_builder import pie_chart
        df = self._load(_TITANIC)
        fig = pie_chart(df, "embarked")
        self._assert_plotly_figure(fig)

    def test_house_prices_correlation_heatmap(self):
        _skip_if_missing(_HOUSE)
        from src.visualization.chart_builder import correlation_heatmap
        df = self._load(_HOUSE)
        fig = correlation_heatmap(df)
        self._assert_plotly_figure(fig)

    def test_house_prices_scatter_plot(self):
        _skip_if_missing(_HOUSE)
        from src.visualization.chart_builder import scatter_plot
        df = self._load(_HOUSE)
        fig = scatter_plot(df, "grlivarea", "saleprice")
        self._assert_plotly_figure(fig)

    def test_house_prices_box_plot(self):
        _skip_if_missing(_HOUSE)
        from src.visualization.chart_builder import box_plot
        df = self._load(_HOUSE)
        fig = box_plot(df, "saleprice")
        self._assert_plotly_figure(fig)

    def test_customers_pair_plot(self):
        _skip_if_missing(_CUSTOMERS)
        from src.visualization.chart_builder import pair_plot
        df = self._load(_CUSTOMERS)
        fig = pair_plot(df)
        self._assert_plotly_figure(fig)

    def test_customers_violin_plot(self):
        _skip_if_missing(_CUSTOMERS)
        from src.visualization.chart_builder import violin_plot
        df = self._load(_CUSTOMERS)
        numeric_cols = df.select_dtypes(include="number").columns.tolist()
        fig = violin_plot(df, numeric_cols[0])
        self._assert_plotly_figure(fig)

    def test_feature_importance_chart(self):
        from src.visualization.chart_builder import feature_importance_chart
        fig = feature_importance_chart(
            feature_names=["feat_a", "feat_b", "feat_c"],
            importances=[0.5, 0.3, 0.2],
        )
        self._assert_plotly_figure(fig)


# ===========================================================================
# 6. MACHINE LEARNING
# ===========================================================================


class TestMLAllDatasets:
    """Verify ML pipeline produces valid metrics for each reference dataset."""

    def _load(self, path: Path) -> pd.DataFrame:
        from src.ingestion.data_loader import DataLoader
        return DataLoader().load(path)

    def test_titanic_classification_metrics(self):
        """Titanic-like dataset: binary classification (survived)."""
        _skip_if_missing(_TITANIC)
        from src.ml.task_detector import TaskType, detect_task
        from src.ml.trainer import train_models
        from src.ml.evaluator import evaluate_model

        df = self._load(_TITANIC)
        task_result = detect_task(df, target_column="survived")
        # Survived has 2 unique values → classification
        assert task_result.task_type == TaskType.CLASSIFICATION

        train_results = train_models(df, "survived", TaskType.CLASSIFICATION)
        assert len(train_results) >= 2

        for tr in train_results:
            metrics = evaluate_model(tr)
            assert metrics.accuracy is not None
            assert 0.0 <= metrics.accuracy <= 1.0
            assert metrics.f1_weighted is not None
            assert metrics.confusion_matrix is not None

    def test_house_prices_regression_metrics(self):
        """House prices dataset: regression (saleprice)."""
        _skip_if_missing(_HOUSE)
        from src.ml.task_detector import TaskType, detect_task
        from src.ml.trainer import train_models
        from src.ml.evaluator import evaluate_model

        df = self._load(_HOUSE)
        task_result = detect_task(df, target_column="saleprice")
        assert task_result.task_type == TaskType.REGRESSION

        train_results = train_models(df, "saleprice", TaskType.REGRESSION)
        assert len(train_results) >= 2

        for tr in train_results:
            metrics = evaluate_model(tr)
            assert metrics.mae is not None
            assert metrics.rmse is not None
            assert metrics.r2 is not None
            assert metrics.rmse >= 0.0

    def test_customers_clustering_metrics(self):
        """Customers dataset: unsupervised clustering (no target)."""
        _skip_if_missing(_CUSTOMERS)
        from src.ml.task_detector import TaskType, detect_task
        from src.ml.trainer import train_models
        from src.ml.evaluator import evaluate_model

        df = self._load(_CUSTOMERS)
        task_result = detect_task(df, target_column=None)
        assert task_result.task_type == TaskType.CLUSTERING

        train_results = train_models(df, None, TaskType.CLUSTERING)
        assert len(train_results) == 1

        metrics = evaluate_model(train_results[0])
        assert metrics.inertia is not None
        assert metrics.inertia >= 0.0
        assert metrics.n_clusters is not None

    def test_feature_importance_titanic(self):
        _skip_if_missing(_TITANIC)
        from src.ml.task_detector import TaskType
        from src.ml.trainer import train_models
        from src.ml.feature_importance import compute_feature_importance

        df = self._load(_TITANIC)
        train_results = train_models(df, "survived", TaskType.CLASSIFICATION)
        rf = next((r for r in train_results if r.model_name == "Random Forest"), train_results[0])
        imp = compute_feature_importance(rf, method="auto", n_repeats=3)
        assert len(imp.ranked) > 0

    def test_feature_importance_house_prices(self):
        _skip_if_missing(_HOUSE)
        from src.ml.task_detector import TaskType
        from src.ml.trainer import train_models
        from src.ml.feature_importance import compute_feature_importance

        df = self._load(_HOUSE)
        train_results = train_models(df, "saleprice", TaskType.REGRESSION)
        rf = next(
            (r for r in train_results if "Random Forest" in r.model_name), train_results[0]
        )
        imp = compute_feature_importance(rf, method="auto", n_repeats=3)
        assert len(imp.ranked) > 0

    def test_metrics_to_dict_serialisable(self):
        _skip_if_missing(_TITANIC)
        import json
        from src.ml.task_detector import TaskType
        from src.ml.trainer import train_models
        from src.ml.evaluator import evaluate_model

        df = self._load(_TITANIC)
        tr = train_models(df, "survived", TaskType.CLASSIFICATION)[0]
        metrics = evaluate_model(tr)
        d = metrics.to_dict()
        json.dumps(d)  # Must not raise


# ===========================================================================
# 7. GENAI — mocked API calls
# ===========================================================================


class TestGenAIMocked:
    """Verify GenAI layer works correctly with mocked watsonx credentials."""

    def test_generate_returns_none_without_credentials(self, monkeypatch):
        """Missing credentials → generate() returns None, no exception raised."""
        monkeypatch.delenv("WATSONX_API_KEY", raising=False)
        monkeypatch.delenv("WATSONX_PROJECT_ID", raising=False)
        from src.genai.watsonx_client import WatsonxClient
        client = WatsonxClient()
        result = client.generate("test prompt")
        assert result is None

    def test_generate_with_mocked_model(self, mock_watsonx_client):
        """Mocked client returns the configured canned response."""
        result = mock_watsonx_client.generate("any prompt")
        assert result == "Mock AI insight generated by watsonx."

    def test_prompt_builder_dataset_summary_contains_stats(self):
        """build_dataset_summary_prompt embeds injected stats verbatim."""
        from src.genai.prompt_builder import build_dataset_summary_prompt
        report = {
            "n_rows": 300,
            "n_cols": 7,
            "n_numeric": 5,
            "n_categorical": 2,
            "missing_cells": 10,
            "missing_pct": 3.33,
            "duplicate_rows": 0,
            "memory_usage_mb": 0.05,
            "numeric_summary": {},
            "top_categories": {},
        }
        prompt = build_dataset_summary_prompt(report)
        assert "300" in prompt
        assert "7" in prompt
        assert isinstance(prompt, str) and len(prompt) > 0

    def test_prompt_builder_model_explanation_contains_metrics(self):
        """build_model_explanation_prompt embeds accuracy verbatim."""
        from src.genai.prompt_builder import build_model_explanation_prompt
        metrics = {
            "task_type": "classification",
            "model_name": "RandomForest",
            "n_samples": 240,
            "n_features": 6,
            "accuracy": 0.85,
            "f1": 0.84,
        }
        prompt = build_model_explanation_prompt(metrics, [])
        assert "0.85" in prompt or "0.850" in prompt

    def test_missing_credentials_handled_gracefully(self, monkeypatch):
        """Application must not raise when credentials are absent."""
        monkeypatch.delenv("WATSONX_API_KEY", raising=False)
        monkeypatch.delenv("WATSONX_PROJECT_ID", raising=False)
        from src.genai.watsonx_client import WatsonxClient
        client = WatsonxClient()
        assert client.is_configured is False
        # Must not raise — returns None gracefully
        result = client.generate("irrelevant prompt")
        assert result is None

    def test_api_error_returns_none_not_raises(self):
        """API errors must be caught and return None instead of raising."""
        from src.genai.watsonx_client import WatsonxClient
        client = WatsonxClient(api_key="k", project_id="p")
        mock_model = MagicMock()
        mock_model.generate_text.side_effect = RuntimeError("connection timeout")
        client._model = mock_model
        result = client.generate("test prompt")
        assert result is None


# ===========================================================================
# 8. NATURAL LANGUAGE QUERY
# ===========================================================================


class TestNLQueryAllDatasets:
    """Verify NL Query returns structured results for each reference dataset."""

    def _load(self, path: Path) -> pd.DataFrame:
        from src.ingestion.data_loader import DataLoader
        return DataLoader().load(path)

    def _engine(self, df: pd.DataFrame, client=None):
        from src.nl_query.nl_query_engine import NLQueryEngine
        return NLQueryEngine(df, watsonx_client=client)

    def test_titanic_count_query(self):
        _skip_if_missing(_TITANIC)
        df = self._load(_TITANIC)
        eng = self._engine(df)
        result = eng.ask("How many rows are in this dataset?")
        assert result.query_type == "COUNT"
        assert result.computed_result["row_count"] == len(df)
        assert result.error is None

    def test_titanic_average_query(self):
        _skip_if_missing(_TITANIC)
        df = self._load(_TITANIC)
        eng = self._engine(df)
        result = eng.ask("What is the average age?")
        assert result.query_type == "AVERAGE"
        assert "age" in result.computed_result
        assert result.error is None

    def test_titanic_summary_query(self):
        _skip_if_missing(_TITANIC)
        df = self._load(_TITANIC)
        eng = self._engine(df)
        result = eng.ask("Give me a summary of the dataset")
        assert result.query_type == "SUMMARY"
        assert "n_rows" in result.computed_result
        assert result.computed_result["n_rows"] == len(df)

    def test_house_prices_correlation_query(self):
        _skip_if_missing(_HOUSE)
        df = self._load(_HOUSE)
        eng = self._engine(df)
        result = eng.ask("What are the strongest correlations?")
        assert result.query_type == "CORRELATION"
        assert isinstance(result.computed_result, list)
        assert result.error is None

    def test_house_prices_sum_query(self):
        _skip_if_missing(_HOUSE)
        df = self._load(_HOUSE)
        eng = self._engine(df)
        result = eng.ask("What is the total saleprice?")
        assert result.query_type == "SUM"
        assert result.error is None

    def test_customers_distribution_query(self):
        _skip_if_missing(_CUSTOMERS)
        df = self._load(_CUSTOMERS)
        eng = self._engine(df)
        result = eng.ask("What is the distribution of age?")
        assert result.query_type == "DISTRIBUTION"
        assert result.error is None
        assert result.computed_result is not None

    def test_nl_query_with_mocked_llm(self, mock_watsonx_client):
        """When a mocked client is provided, explanation must be the mock's return value."""
        _skip_if_missing(_TITANIC)
        df = self._load(_TITANIC)
        eng = self._engine(df, client=mock_watsonx_client)
        result = eng.ask("How many rows are in this dataset?")
        assert result.explanation == "Mock AI insight generated by watsonx."
        mock_watsonx_client.generate.assert_called_once()

    def test_nl_query_without_client_returns_no_explanation(self):
        _skip_if_missing(_TITANIC)
        df = self._load(_TITANIC)
        eng = self._engine(df, client=None)
        result = eng.ask("How many rows?")
        assert result.explanation is None
        assert result.computed_result is not None

    def test_nl_query_result_structure_is_complete(self):
        _skip_if_missing(_CUSTOMERS)
        df = self._load(_CUSTOMERS)
        from src.nl_query.nl_query_engine import NLQueryResult
        eng = self._engine(df)
        result = eng.ask("Summarise the dataset")
        assert isinstance(result, NLQueryResult)
        assert result.question is not None
        assert result.query_type is not None


# ===========================================================================
# 9. REPORTING
# ===========================================================================


class TestReportingAllDatasets:
    """Verify reporting produces valid HTML for each reference dataset."""

    def _load(self, path: Path) -> pd.DataFrame:
        from src.ingestion.data_loader import DataLoader
        return DataLoader().load(path)

    def _build_minimal_context(self, df: pd.DataFrame, dataset_name: str) -> dict:
        """Build a minimal but realistic context from a loaded DataFrame."""
        from src.profiling.data_profiler import profile_dataframe
        from src.eda.eda_engine import run_eda

        profile = profile_dataframe(df)
        eda = run_eda(df)

        return {
            "title": f"Integration Test Report — {dataset_name}",
            "dataset_name": dataset_name,
            "profile": profile,
            "eda": {
                "top_correlations": [],
                "skewed_columns": [],
                "charts": [],
            },
        }

    def test_titanic_report_generates_valid_html(self, tmp_path):
        _skip_if_missing(_TITANIC)
        from src.reporting.report_generator import ReportGenerator
        df = self._load(_TITANIC)
        ctx = self._build_minimal_context(df, "titanic_like.csv")
        gen = ReportGenerator(output_dir=tmp_path)
        html_path = gen.generate(ctx)
        assert Path(html_path).exists()
        content = Path(html_path).read_text(encoding="utf-8")
        assert "<html" in content.lower() or "<!doctype html>" in content.lower()

    def test_house_prices_report_generates_valid_html(self, tmp_path):
        _skip_if_missing(_HOUSE)
        from src.reporting.report_generator import ReportGenerator
        df = self._load(_HOUSE)
        ctx = self._build_minimal_context(df, "house_prices.csv")
        gen = ReportGenerator(output_dir=tmp_path)
        html_path = gen.generate(ctx)
        content = Path(html_path).read_text(encoding="utf-8")
        assert len(content) > 0
        assert "house_prices.csv" in content

    def test_customers_report_generates_valid_html(self, tmp_path):
        _skip_if_missing(_CUSTOMERS)
        from src.reporting.report_generator import ReportGenerator
        df = self._load(_CUSTOMERS)
        ctx = self._build_minimal_context(df, "customers.csv")
        gen = ReportGenerator(output_dir=tmp_path)
        html_path = gen.generate(ctx)
        content = Path(html_path).read_text(encoding="utf-8")
        assert "customers.csv" in content

    def test_report_contains_profile_data(self, tmp_path):
        _skip_if_missing(_TITANIC)
        from src.reporting.report_generator import ReportGenerator
        df = self._load(_TITANIC)
        ctx = self._build_minimal_context(df, "titanic_like.csv")
        gen = ReportGenerator(output_dir=tmp_path)
        html = gen.render_html(ctx)
        # Row count must appear in the report
        assert str(df.shape[0]) in html

    def test_report_with_ml_metrics_included(self, tmp_path):
        _skip_if_missing(_TITANIC)
        from src.reporting.report_generator import ReportGenerator
        df = self._load(_TITANIC)
        ctx = self._build_minimal_context(df, "titanic_like.csv")
        ctx["ml_metrics"] = {
            "task_type": "classification",
            "model_name": "RandomForestClassifier",
            "accuracy": 0.82,
            "f1_weighted": 0.81,
            "cv_mean": 0.80,
            "cv_std": 0.03,
            "charts": [],
        }
        gen = ReportGenerator(output_dir=tmp_path)
        html = gen.render_html(ctx)
        assert "RandomForestClassifier" in html
        # The template renders accuracy as a percentage (e.g. "82.0%") via num_fmt
        assert "82" in html

    def test_report_with_genai_insights_included(self, tmp_path):
        _skip_if_missing(_TITANIC)
        from src.reporting.report_generator import ReportGenerator
        df = self._load(_TITANIC)
        ctx = self._build_minimal_context(df, "titanic_like.csv")
        ctx["genai_insights"] = {
            "Dataset Summary": "Mock insight: 300 passengers, 38% survived.",
        }
        gen = ReportGenerator(output_dir=tmp_path)
        html = gen.render_html(ctx)
        assert "Mock insight" in html

    def test_report_with_nl_query_results_included(self, tmp_path):
        _skip_if_missing(_TITANIC)
        from src.reporting.report_generator import ReportGenerator
        df = self._load(_TITANIC)
        ctx = self._build_minimal_context(df, "titanic_like.csv")
        ctx["nl_query_results"] = [
            {
                "question": "How many rows?",
                "query_type": "COUNT",
                "computed_result": {"row_count": len(df)},
                "explanation": "There are 300 rows in this dataset.",
                "error": None,
            }
        ]
        gen = ReportGenerator(output_dir=tmp_path)
        html = gen.render_html(ctx)
        assert "How many rows?" in html

    def test_render_html_is_self_contained(self, tmp_path):
        """No external HTTP resources should be referenced."""
        import re
        _skip_if_missing(_HOUSE)
        from src.reporting.report_generator import ReportGenerator
        df = self._load(_HOUSE)
        ctx = self._build_minimal_context(df, "house_prices.csv")
        gen = ReportGenerator(output_dir=tmp_path)
        html = gen.render_html(ctx)
        external_scripts = re.findall(r'<script[^>]+src=["\']https?://', html, re.I)
        external_links = re.findall(r'<link[^>]+href=["\']https?://', html, re.I)
        assert external_scripts == []
        assert external_links == []


# ===========================================================================
# 10. FULL END-TO-END PIPELINE SMOKE TESTS
# ===========================================================================


class TestFullPipelineEndToEnd:
    """Complete pipeline smoke tests: Ingestion → Reporting for each dataset."""

    def _run_pipeline(
        self,
        dataset_path: Path,
        target_column: str | None,
        task_type_override=None,
        mock_client=None,
    ) -> dict:
        """Execute the full pipeline and return a context dict suitable for reporting."""
        from src.ingestion.data_loader import DataLoader
        from src.preprocessing.preprocessor import run_preprocessing
        from src.profiling.data_profiler import profile_dataframe
        from src.eda.eda_engine import run_eda
        from src.ml.task_detector import detect_task, TaskType
        from src.ml.trainer import train_models
        from src.ml.evaluator import evaluate_model
        from src.ml.feature_importance import compute_feature_importance
        from src.nl_query.nl_query_engine import NLQueryEngine
        from src.reporting.report_generator import ReportGenerator

        # 1. Ingestion
        df_raw = DataLoader().load(dataset_path)
        assert isinstance(df_raw, pd.DataFrame) and not df_raw.empty

        # 2. Profiling (on raw data — before aggressive preprocessing)
        profile = profile_dataframe(df_raw)
        assert "shape" in profile

        # 3. EDA (on raw data)
        eda_result = run_eda(df_raw, target_column=target_column)
        assert "univariate" in eda_result

        # 4. Preprocessing
        df_proc, preproc_summary = run_preprocessing(df_raw)
        assert isinstance(df_proc, pd.DataFrame) and not df_proc.empty

        # 5. Task detection
        task_det = detect_task(df_raw, target_column=target_column,
                               user_override=task_type_override)
        task_type = task_det.task_type

        # 6. ML training + evaluation
        train_results = train_models(df_raw, target_column, task_type)
        assert len(train_results) >= 1
        best_result = train_results[0]
        metrics = evaluate_model(best_result)
        imp = compute_feature_importance(best_result, method="auto", n_repeats=3)

        # 7. NL Query (no LLM — deterministic only)
        eng = NLQueryEngine(df_raw, watsonx_client=mock_client)
        nl_result = eng.ask("How many rows are in this dataset?")
        assert nl_result.error is None
        assert nl_result.computed_result["row_count"] == len(df_raw)

        # 8. Build reporting context
        context = {
            "title": f"Pipeline Test — {dataset_path.name}",
            "dataset_name": dataset_path.name,
            "profile": profile,
            "eda": {
                "top_correlations": [],
                "skewed_columns": [],
                "charts": [],
            },
            "ml_metrics": {
                **metrics.to_dict(),
                "charts": [],
            },
            "feature_importance": {
                "entries": [
                    {"feature": e.feature, "importance": e.importance}
                    for e in imp.ranked[:10]
                ],
                "chart": None,
            },
            "nl_query_results": [nl_result],
        }

        return context

    def test_titanic_full_pipeline(self, tmp_path, mock_watsonx_client):
        _skip_if_missing(_TITANIC)
        from src.ml.task_detector import TaskType
        from src.reporting.report_generator import ReportGenerator

        ctx = self._run_pipeline(
            _TITANIC,
            target_column="survived",
            task_type_override=TaskType.CLASSIFICATION,
            mock_client=mock_watsonx_client,
        )

        gen = ReportGenerator(output_dir=tmp_path)
        html_path = gen.generate(ctx)
        assert Path(html_path).exists()
        content = Path(html_path).read_text(encoding="utf-8")
        assert "<html" in content.lower() or "<!doctype" in content.lower()
        assert "titanic_like.csv" in content

    def test_house_prices_full_pipeline(self, tmp_path, mock_watsonx_client):
        _skip_if_missing(_HOUSE)
        from src.ml.task_detector import TaskType
        from src.reporting.report_generator import ReportGenerator

        ctx = self._run_pipeline(
            _HOUSE,
            target_column="saleprice",
            task_type_override=TaskType.REGRESSION,
            mock_client=mock_watsonx_client,
        )

        gen = ReportGenerator(output_dir=tmp_path)
        html_path = gen.generate(ctx)
        assert Path(html_path).exists()
        content = Path(html_path).read_text(encoding="utf-8")
        assert "house_prices.csv" in content

    def test_customers_full_pipeline(self, tmp_path, mock_watsonx_client):
        _skip_if_missing(_CUSTOMERS)
        from src.ml.task_detector import TaskType
        from src.reporting.report_generator import ReportGenerator

        ctx = self._run_pipeline(
            _CUSTOMERS,
            target_column=None,
            task_type_override=TaskType.CLUSTERING,
            mock_client=mock_watsonx_client,
        )

        gen = ReportGenerator(output_dir=tmp_path)
        html_path = gen.generate(ctx)
        assert Path(html_path).exists()
        content = Path(html_path).read_text(encoding="utf-8")
        assert "customers.csv" in content

    def test_pipeline_report_is_valid_html(self, tmp_path, mock_watsonx_client):
        """The report HTML must be well-formed (has doctype/html tag)."""
        _skip_if_missing(_TITANIC)
        from src.ml.task_detector import TaskType
        from src.reporting.report_generator import ReportGenerator

        ctx = self._run_pipeline(
            _TITANIC,
            target_column="survived",
            task_type_override=TaskType.CLASSIFICATION,
            mock_client=mock_watsonx_client,
        )
        gen = ReportGenerator(output_dir=tmp_path)
        html = gen.render_html(ctx)
        assert "<!DOCTYPE html>" in html or "<!doctype html>" in html.lower()

    def test_pipeline_nl_query_count_correct_for_each_dataset(self):
        """NL count query must return the exact number of rows per dataset."""
        from src.ingestion.data_loader import DataLoader
        from src.nl_query.nl_query_engine import NLQueryEngine

        loader = DataLoader()
        for path in [_TITANIC, _HOUSE, _CUSTOMERS]:
            _skip_if_missing(path)
            df = loader.load(path)
            eng = NLQueryEngine(df)
            result = eng.ask("How many rows are there?")
            assert result.computed_result["row_count"] == len(df), (
                f"{path.name}: expected {len(df)} rows, "
                f"got {result.computed_result['row_count']}"
            )
