"""
Natural Language Query Engine.

Design
------
User questions are classified by keyword/regex patterns into one of a fixed set
of *query types*.  Each query type maps to a deterministic Pandas operation
that is executed against the supplied DataFrame.  The computed result is then
passed to ``prompt_builder.build_nl_query_prompt()`` together with the
original question, and the LLM is asked only to produce natural-language
commentary around that pre-computed number.

The LLM is **never** asked to calculate, infer, or estimate numerical values.

Supported query types
---------------------
AVERAGE          — "what is the average / mean of <col>"
SUM              — "what is the total / sum of <col>"
MAX_CATEGORY     — "which category has the highest / most <col>"
COUNT            — "how many records / rows"
DISTRIBUTION     — "what is the distribution of <col>"
CORRELATION      — "strongest correlations / most correlated"
SUMMARY          — "summarise / describe the dataset"
UNSUPPORTED      — anything that does not match a known pattern

Public API
----------
NLQueryEngine(df, watsonx_client=None)
    .ask(question: str) -> NLQueryResult
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

import pandas as pd


# ---------------------------------------------------------------------------
# Result type
# ---------------------------------------------------------------------------


@dataclass
class NLQueryResult:
    """Structured result returned by :meth:`NLQueryEngine.ask`.

    Attributes
    ----------
    question:
        The original free-text question posed by the user.
    query_type:
        Classified query type string (e.g. ``"AVERAGE"``, ``"UNSUPPORTED"``).
    computed_result:
        The deterministically computed value(s) from Pandas — never produced by
        an LLM.
    explanation:
        Natural-language commentary generated by the LLM, or ``None`` when the
        client is unconfigured or the query is unsupported.
    error:
        Human-readable error message when the query could not be executed.
    """

    question: str
    query_type: str
    computed_result: Any = None
    explanation: str | None = None
    error: str | None = None


# ---------------------------------------------------------------------------
# Query type constants
# ---------------------------------------------------------------------------

QT_AVERAGE = "AVERAGE"
QT_SUM = "SUM"
QT_MAX_CATEGORY = "MAX_CATEGORY"
QT_COUNT = "COUNT"
QT_DISTRIBUTION = "DISTRIBUTION"
QT_CORRELATION = "CORRELATION"
QT_SUMMARY = "SUMMARY"
QT_UNSUPPORTED = "UNSUPPORTED"


# ---------------------------------------------------------------------------
# Regex patterns used for classification (order matters — checked top-down)
# ---------------------------------------------------------------------------

_PATTERNS: list[tuple[str, re.Pattern[str]]] = [
    # COUNT — must come before AVERAGE / SUM to avoid "how many values" matching SUM
    (QT_COUNT, re.compile(
        r"\b(how many|count|number of|total number|total count|"
        r"n rows|num rows|row count|record count|size of|how large)\b",
        re.IGNORECASE,
    )),
    # AVERAGE
    (QT_AVERAGE, re.compile(
        r"\b(average|avg|mean|typical|median)\b",
        re.IGNORECASE,
    )),
    # SUM
    (QT_SUM, re.compile(
        r"\b(total|sum|aggregate|cumulative|combined)\b",
        re.IGNORECASE,
    )),
    # CORRELATION -- must come before MAX_CATEGORY so "most correlated" /
    # "strongest correlations" are not captured by MAX_CATEGORY first.
    (QT_CORRELATION, re.compile(
        r"\b(correlations?|correlate[sd]?|relationship between|"
        r"related to|strongest relationship|most related|most correlated|"
        r"strongest correlations?)\b",
        re.IGNORECASE,
    )),
    # MAX_CATEGORY -- "which category / group / value has the highest / most"
    (QT_MAX_CATEGORY, re.compile(
        r"\b(which|what).{0,40}(highest|most|largest|maximum|top|biggest|"
        r"best|peak|greatest)\b"
        r"|\b(highest|most|largest|maximum|top|biggest|best|peak|greatest)"
        r".{0,40}(category|group|value|item|entry|class|label)\b",
        re.IGNORECASE,
    )),
    # DISTRIBUTION
    (QT_DISTRIBUTION, re.compile(
        r"\b(distribution|spread|breakdown|frequency|histogram|"
        r"value counts|how is .{1,30} distributed)\b",
        re.IGNORECASE,
    )),
    # SUMMARY
    (QT_SUMMARY, re.compile(
        r"\b(summarise|summarize|summary|describe|overview|"
        r"tell me about|what does|about this dataset|what is in)\b",
        re.IGNORECASE,
    )),
]


# ---------------------------------------------------------------------------
# Column extraction helper
# ---------------------------------------------------------------------------

def _extract_column(question: str, columns: list[str]) -> str | None:
    """Return the first column name mentioned in *question*, or ``None``.

    Matching is case-insensitive and uses word-boundary checks to avoid
    partial matches (e.g. 'age' inside 'average').
    """
    q_lower = question.lower()
    # Sort longest-first so "total_sales" is matched before "sales"
    for col in sorted(columns, key=len, reverse=True):
        pattern = re.compile(r"\b" + re.escape(col.lower()) + r"\b")
        if pattern.search(q_lower):
            return col
    return None


# ---------------------------------------------------------------------------
# Prompt builder integration
# ---------------------------------------------------------------------------

def build_nl_query_prompt(
    question: str,
    query_type: str,
    computed_result: Any,
) -> str:
    """Build a deterministic-firewall prompt for the NL query result.

    All numbers come from *computed_result* — the LLM is never asked to
    calculate anything.

    Parameters
    ----------
    question:
        The original user question.
    query_type:
        The classified query type (e.g. ``"AVERAGE"``).
    computed_result:
        The pre-computed value(s) from Pandas.

    Returns
    -------
    str
        A fully formed prompt string ready for ``WatsonxClient.generate()``.
    """
    result_str = _format_result(computed_result)
    return (
        "You are a data analyst explaining results to a non-technical business audience.\n\n"
        "The following result was computed deterministically by a data analysis tool. "
        "Do not recalculate, alter, or introduce any number not shown below.\n\n"
        "=== Query Details (pre-computed) ===\n"
        f"Question: {question}\n"
        f"Query type: {query_type}\n"
        f"Computed result:\n{result_str}\n\n"
        "=== Task ===\n"
        "In 2–4 sentences, explain what this result means in plain business language. "
        "Reference only the numbers shown above. Do not introduce any numbers not listed."
    )


def _format_result(result: Any) -> str:
    """Convert a computed result to a readable multi-line string."""
    if isinstance(result, dict):
        lines = [f"  {k}: {v}" for k, v in result.items()]
        return "\n".join(lines)
    if isinstance(result, (list, tuple)):
        lines = [f"  {item}" for item in result]
        return "\n".join(lines)
    if isinstance(result, pd.Series):
        lines = [f"  {idx}: {val}" for idx, val in result.items()]
        return "\n".join(lines) or "  (empty)"
    return f"  {result}"


# ---------------------------------------------------------------------------
# Main engine
# ---------------------------------------------------------------------------


class NLQueryEngine:
    """Execute natural-language questions against a Pandas DataFrame.

    Parameters
    ----------
    df:
        The dataset to query.  Must be a non-empty ``pd.DataFrame``.
    watsonx_client:
        Optional :class:`src.genai.watsonx_client.WatsonxClient` instance.
        When ``None`` or unconfigured the engine still returns computed
        results but ``explanation`` will be ``None``.
    """

    def __init__(
        self,
        df: pd.DataFrame,
        watsonx_client: Any | None = None,
    ) -> None:
        if not isinstance(df, pd.DataFrame):
            raise TypeError("df must be a pandas DataFrame")
        self._df = df
        self._client = watsonx_client
        self._columns = list(df.columns)
        self._numeric_cols = list(df.select_dtypes(include="number").columns)
        self._categorical_cols = list(
            df.select_dtypes(include=["object", "category"]).columns
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def ask(self, question: str) -> NLQueryResult:
        """Answer *question* deterministically and return an :class:`NLQueryResult`.

        Parameters
        ----------
        question:
            Free-text question in natural language.

        Returns
        -------
        NLQueryResult
            Always returns a result object — never raises.
        """
        if not question or not question.strip():
            return NLQueryResult(
                question=question,
                query_type=QT_UNSUPPORTED,
                error="Empty question.",
            )

        query_type = self._classify(question)

        try:
            computed_result = self._execute(query_type, question)
        except Exception as exc:  # noqa: BLE001
            return NLQueryResult(
                question=question,
                query_type=query_type,
                error=f"Query execution failed: {exc}",
            )

        explanation = self._explain(question, query_type, computed_result)

        return NLQueryResult(
            question=question,
            query_type=query_type,
            computed_result=computed_result,
            explanation=explanation,
        )

    # ------------------------------------------------------------------
    # Classification
    # ------------------------------------------------------------------

    def _classify(self, question: str) -> str:
        """Return the query type string for *question*."""
        for query_type, pattern in _PATTERNS:
            if pattern.search(question):
                return query_type
        return QT_UNSUPPORTED

    # ------------------------------------------------------------------
    # Execution
    # ------------------------------------------------------------------

    def _execute(self, query_type: str, question: str) -> Any:
        """Dispatch to the appropriate deterministic Pandas operation."""
        dispatch = {
            QT_COUNT: self._exec_count,
            QT_AVERAGE: self._exec_average,
            QT_SUM: self._exec_sum,
            QT_MAX_CATEGORY: self._exec_max_category,
            QT_DISTRIBUTION: self._exec_distribution,
            QT_CORRELATION: self._exec_correlation,
            QT_SUMMARY: self._exec_summary,
            QT_UNSUPPORTED: self._exec_unsupported,
        }
        handler = dispatch.get(query_type, self._exec_unsupported)
        return handler(question)

    def _exec_count(self, question: str) -> dict[str, int]:  # noqa: ARG002
        return {"row_count": len(self._df)}

    def _exec_average(self, question: str) -> dict[str, float]:
        col = _extract_column(question, self._numeric_cols)
        if col:
            return {col: round(float(self._df[col].mean()), 6)}
        # Return means for all numeric columns
        return {c: round(float(self._df[c].mean()), 6) for c in self._numeric_cols}

    def _exec_sum(self, question: str) -> dict[str, float]:
        col = _extract_column(question, self._numeric_cols)
        if col:
            return {col: round(float(self._df[col].sum()), 6)}
        return {c: round(float(self._df[c].sum()), 6) for c in self._numeric_cols}

    def _exec_max_category(self, question: str) -> dict[str, Any]:
        # Try to find a categorical column mentioned in the question
        cat_col = _extract_column(question, self._categorical_cols)
        num_col = _extract_column(question, self._numeric_cols)

        if cat_col and num_col:
            # "which category in <cat_col> has the highest <num_col>"
            grouped = self._df.groupby(cat_col)[num_col].sum()
            top_cat = str(grouped.idxmax())
            top_val = round(float(grouped.max()), 6)
            return {
                "category_column": cat_col,
                "value_column": num_col,
                "top_category": top_cat,
                "top_value": top_val,
            }

        if cat_col:
            # Count-based: which value in <cat_col> appears most
            counts = self._df[cat_col].value_counts()
            return {
                "category_column": cat_col,
                "top_category": str(counts.index[0]),
                "count": int(counts.iloc[0]),
            }

        if num_col:
            # Simple max of numeric column
            return {
                "value_column": num_col,
                "max_value": round(float(self._df[num_col].max()), 6),
            }

        # Fallback: frequency mode for the first categorical column
        if self._categorical_cols:
            col = self._categorical_cols[0]
            counts = self._df[col].value_counts()
            return {
                "category_column": col,
                "top_category": str(counts.index[0]),
                "count": int(counts.iloc[0]),
            }

        # All-numeric fallback: column with highest mean
        if self._numeric_cols:
            means = {c: float(self._df[c].mean()) for c in self._numeric_cols}
            top_col = max(means, key=means.__getitem__)
            return {
                "column_with_highest_mean": top_col,
                "mean_value": round(means[top_col], 6),
            }

        return {}

    def _exec_distribution(self, question: str) -> dict[str, Any]:
        col = _extract_column(question, self._columns)
        if col is None:
            # Default to first available column
            col = self._columns[0] if self._columns else None

        if col is None:
            return {}

        if col in self._numeric_cols:
            s = self._df[col].dropna()
            return {
                "column": col,
                "mean": round(float(s.mean()), 6),
                "std": round(float(s.std()), 6),
                "min": round(float(s.min()), 6),
                "25%": round(float(s.quantile(0.25)), 6),
                "median": round(float(s.median()), 6),
                "75%": round(float(s.quantile(0.75)), 6),
                "max": round(float(s.max()), 6),
            }

        # Categorical: top value counts (up to 10)
        counts = self._df[col].value_counts().head(10)
        return {
            "column": col,
            "value_counts": {str(k): int(v) for k, v in counts.items()},
        }

    def _exec_correlation(self, question: str) -> list[dict[str, Any]]:  # noqa: ARG002
        if len(self._numeric_cols) < 2:
            return []
        corr_matrix = self._df[self._numeric_cols].corr()
        pairs: list[dict[str, Any]] = []
        seen: set[frozenset[str]] = set()
        for col_a in self._numeric_cols:
            for col_b in self._numeric_cols:
                if col_a == col_b:
                    continue
                key = frozenset({col_a, col_b})
                if key in seen:
                    continue
                seen.add(key)
                val = corr_matrix.loc[col_a, col_b]
                if pd.notna(val):
                    pairs.append({
                        "feature_a": col_a,
                        "feature_b": col_b,
                        "correlation": round(float(val), 4),
                    })
        pairs.sort(key=lambda x: abs(x["correlation"]), reverse=True)
        return pairs[:10]

    def _exec_summary(self, question: str) -> dict[str, Any]:  # noqa: ARG002
        result: dict[str, Any] = {
            "n_rows": int(len(self._df)),
            "n_cols": int(len(self._df.columns)),
            "n_numeric": int(len(self._numeric_cols)),
            "n_categorical": int(len(self._categorical_cols)),
            "missing_cells": int(self._df.isna().sum().sum()),
            "missing_pct": round(
                float(self._df.isna().sum().sum()) / max(self._df.size, 1) * 100, 4
            ),
            "duplicate_rows": int(self._df.duplicated().sum()),
        }
        if self._numeric_cols:
            result["numeric_means"] = {
                c: round(float(self._df[c].mean()), 6) for c in self._numeric_cols
            }
        return result

    def _exec_unsupported(self, question: str) -> None:  # noqa: ARG002
        return None

    # ------------------------------------------------------------------
    # Explanation (LLM call, respects deterministic firewall)
    # ------------------------------------------------------------------

    def _explain(
        self,
        question: str,
        query_type: str,
        computed_result: Any,
    ) -> str | None:
        if query_type == QT_UNSUPPORTED or computed_result is None:
            return None
        if self._client is None:
            return None
        prompt = build_nl_query_prompt(question, query_type, computed_result)
        return self._client.generate(prompt)
